////// MASSAGES
export const CREATE_MASSAGES = 'CREATE_MASSAGES'
export const SUCCESS_MASSAGES = 'SUCCESS_MASSAGES'
export const ERROR_MASSAGES = 'ERROR_MASSAGES'
export const WARNING_MASSAGES = 'WARNING_MASSAGES'
////// USER
////// USER-LOGIN
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'//????
////// USER-LOGOUT
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
////// USER-LOAD_USER
export const USER_LOADING = 'USER_LOADING'
export const USER_LOADED = 'USER_LOADED'
export const USER_EXPIRED = 'USER_EXPIRED'
////// BIODATA
////// BIODATA-LOADING
export const BIODATA_LOADING = 'BIODATA_LOADING'
////// BIODATA-LOAD_DETAIL
export const _BUTTON_DETAIL_VIEW_ = '_BUTTON_DETAIL_VIEW_'
export const BIODATA_DETAIL_LOADED = 'BIODATA_DETAIL_LOADED'
export const BIODATA_ACCOUNT_DETAIL_LOADED = 'BIODATA_ACCOUNT_DETAIL_LOADED'
////// BIODATA-UPDATE_BIODATA
export const _BUTTON_UPDATE_BIODATA_ = '_BUTTON_UPDATE_BIODATA_'
export const BIODATA_UPDATE_DATA_LOADED = 'BIODATA_UPDATE_DATA_LOADED'
export const BIODATA_UPDATED = 'BIODATA_UPDATED'
////// BIODATA-DELETE
export const BIODATA_DELETED = 'BIODATA_DELETED'
////// BIODATA-UPDATE_BIODATA_ACCOUNT
export const _BUTTON_UPDATE_BIODATA_ACCOUNT_ = '_BUTTON_UPDATE_BIODATA_ACCOUNT_'
export const BIODATA_ACCOUNT_UPDATE_DATA_LOADED = 'BIODATA_ACCOUNT_UPDATE_DATA_LOADED'
export const BIODATA_ACCOUNT_UPDATED = 'BIODATA_ACCOUNT_UPDATED'
////// BIODATA-BIODATA.SISWA
export const SISWA_DATA_LOADED = 'SISWA_DATA_LOADED'
////// BIODATA-BIODATA.SISWA-CREATE
export const SISWA_BIODATA_CREATED = 'SISWA_BIODATA_CREATED'
export const SISWA_BIODATA_FAILED_CREATE = 'SISWA_BIODATA_FAILED_CREATE'
export const SISWA_ACCOUNT_CREATED = 'SISWA_ACCOUNT_CREATED'
export const SISWA_ACCOUNT_FAILED_CREATE = 'SISWA_ACCOUNT_FAILED_CREATE'
export const SISWA_FULLY_CREATED = 'SISWA_FULLY_CREATED'


