export const CREATE_MASSAGES = 'CREATE_MASSAGES'

export const USER_LOADING = 'USER_LOADING'
export const USER_LOADED = 'USER_LOADED'
export const USER_EXPIRED = 'USER_EXPIRED'
export const CONVERT_TO_USER = 'CONVERT_TO_USER'

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'

export const BIODATA_LOADED = 'BIODATA_LOADED'
export const BIODATA_ACCOUNT_LOADED = 'BIODATA_ACCOUNT_LOADED'


