export const CREATE_MASSAGES = 'CREATE_MASSAGES'
export const SUCCESS_MASSAGES = 'SUCCESS_MASSAGES'
export const ERROR_MASSAGES = 'ERROR_MASSAGES'
export const WARNING_MASSAGES = 'WARNING_MASSAGES'

export const USER_LOADING = 'USER_LOADING'
export const USER_LOADED = 'USER_LOADED'
export const USER_EXPIRED = 'USER_EXPIRED'
export const CONVERT_TO_USER = 'CONVERT_TO_USER'

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'

export const BIODATA_LOADED = 'BIODATA_LOADED'
export const BIODATA_ACCOUNT_LOADED = 'BIODATA_ACCOUNT_LOADED'
export const BIODATA_UPDATE_LOADED = 'BIODATA_UPDATE_LOADED'
export const BIODATA_UPDATED = 'BIODATA_UPDATED'
export const SISWA_DATA_LOADED = 'SISWA_DATA_LOADED'
export const _BUTTON_UPDATE_BIODATA_ = '_BUTTON_UPDATE_BIODATA_'


