# Generated by Django 3.0.4 on 2020-05-15 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instansi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nama_Instansi', models.CharField(max_length=60, unique=True)),
                ('Jenis_Instansi', models.CharField(max_length=30)),
                ('Keterangan_Instansi', models.TextField(blank=True, max_length=240, null=True)),
            ],
        ),
    ]
