# Generated by Django 3.0.4 on 2020-05-20 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0006_auto_20200322_1313'),
        ('prestasi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestasi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nama_Pengaju', models.CharField(max_length=100)),
                ('Tanggal_Pengajuan', models.DateTimeField(auto_now_add=True)),
                ('Nama_Dituju', models.CharField(max_length=100)),
                ('Point_Awal_Dituju', models.PositiveSmallIntegerField()),
                ('Nama_Prestasi', models.CharField(max_length=240)),
                ('No_Sertifikat', models.CharField(blank=True, max_length=100, null=True)),
                ('Katagori_Prestasi', models.CharField(blank=True, choices=[('Menunggu', 'Menunggu'), ('Rejected', 'Rejected'), ('Accepted', 'Accepted')], default=None, max_length=11, null=True)),
                ('Tingkatan_Prestasi', models.CharField(choices=[('Remisi', 'Remisi'), ('RT/RW/Kelurahan', 'RT/RW/Kelurahan'), ('Sekolah', 'Sekolah'), ('Kota', 'Kota'), ('Provinsi', 'Provinsi'), ('Nasional', 'Nasional'), ('Internasional', 'Internasional')], max_length=20)),
                ('Lampiran', models.ImageField(blank=True, null=True, upload_to='PrestasiLampiran')),
                ('Keterangan', models.TextField(blank=True, default=None, max_length=240, null=True)),
                ('Status', models.CharField(choices=[('Menunggu', 'Menunggu'), ('Rejected', 'Rejected'), ('Accepted', 'Accepted')], default='Menunggu', max_length=11)),
                ('Nama_Assessor', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('Tanggal_Diterima', models.DateTimeField(blank=True, default=None, null=True)),
                ('Point_Akhir', models.SmallIntegerField(blank=True, default=None, null=True)),
                ('Nama_Instansi', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='prestasi.Instansi')),
                ('Nomer_Induk_Assessor', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='PrestasiAssessor', to='biodata.Biodata', to_field='NomerInduk')),
                ('Nomer_Induk_Dituju', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='PrestasiDituju', to='biodata.Biodata', to_field='NomerInduk')),
                ('Nomer_Induk_Pengaju', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='PrestasiPengaju', to='biodata.Biodata', to_field='NomerInduk')),
            ],
        ),
    ]
