# Generated by Django 3.0.4 on 2020-05-20 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prestasi', '0003_prestasi_prestasi_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestasi',
            name='Katagori_Prestasi',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='prestasi',
            name='Nama_Instansi',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='PrestasiNamaInstansi', to='prestasi.Instansi', to_field='Nama_Instansi'),
        ),
    ]
