# Generated by Django 3.0.4 on 2020-03-19 13:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nomerinduk', models.CharField(max_length=50, unique=True, verbose_name='nomerinduk')),
                ('active', models.BooleanField(default=True)),
                ('siswa', models.BooleanField(default=False)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('supervisor', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
