# Generated by Django 3.0.4 on 2020-03-20 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.OneToOneField(default='f6bfec3e9c2440a3b2d8dde91b11a8e9', on_delete=django.db.models.deletion.CASCADE, to='biodata.Biodata'),
            preserve_default=False,
        ),
    ]
