# Generated by Django 3.0.4 on 2020-05-15 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0006_auto_20200322_1313'),
        ('account', '0004_auto_20200505_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='biodata.Biodata'),
            preserve_default=False,
        ),
    ]
