# Generated by Django 3.0.4 on 2020-04-08 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelanggaran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NamaPelanggaran', models.CharField(max_length=60, unique=True)),
                ('JenisPelanggaran', models.CharField(choices=[('Ringan', 'Ringan'), ('Sedang', 'Sedang'), ('Berat', 'Berat')], max_length=10)),
                ('KeteranganPelanggaran', models.TextField(blank=True, max_length=240, null=True)),
                ('PelanggaranPoint', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
