# Generated by Django 3.0.4 on 2020-04-08 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0006_auto_20200322_1313'),
        ('point', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TanggalPengajuan', models.DateTimeField(auto_now_add=True)),
                ('PointAkhir', models.PositiveSmallIntegerField(default='asd')),
                ('NomerIndukPengaju', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='biodata.Biodata')),
            ],
        ),
    ]
