# Generated by Django 3.0.4 on 2020-04-08 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0006_auto_20200322_1313'),
        ('point', '0002_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='NomerIndukPengaju',
            field=models.ForeignKey(db_column='Biodata_id', on_delete=django.db.models.deletion.DO_NOTHING, to='biodata.Biodata'),
        ),
    ]
