# Generated by Django 3.0.4 on 2020-04-08 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0006_auto_20200322_1313'),
        ('point', '0003_auto_20200408_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='NomerIndukPengaju',
            field=models.ForeignKey(db_column='Biodata_Nama', on_delete=django.db.models.deletion.DO_NOTHING, to='biodata.Biodata'),
        ),
        migrations.AlterField(
            model_name='point',
            name='PointAkhir',
            field=models.PositiveSmallIntegerField(default=123),
        ),
    ]
