# Generated by Django 3.0.4 on 2020-04-09 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0005_auto_20200408_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='JenisPelanggaran',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='point',
            name='Lampiran',
            field=models.ImageField(blank=True, null=True, upload_to='PointLampiran'),
        ),
        migrations.AddField(
            model_name='point',
            name='NamaAssessor',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='point',
            name='NamaDituju',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='point',
            name='NamaPelanggaran',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='point.Pelanggaran'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='point',
            name='NamaPengaju',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='point',
            name='NomerIndukAssessor',
            field=models.CharField(blank=True, default=None, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='point',
            name='NomerIndukDituju',
            field=models.CharField(default='', max_length=70),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='point',
            name='PointAwalDituju',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='point',
            name='PointPengurang',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='point',
            name='Status',
            field=models.CharField(choices=[('Menunggu', 'Menunggu'), ('Dibatalkan', 'Dibatalkan'), ('Diterima', 'Diterima')], default='Menunggu', max_length=11),
        ),
        migrations.AddField(
            model_name='point',
            name='TanggalDiterima',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='point',
            name='NomerIndukPengaju',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='point',
            name='PointAkhir',
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
    ]
