# Generated by Django 3.0.4 on 2020-04-09 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0007_auto_20200410_0615'),
    ]

    operations = [
        migrations.RenameField(
            model_name='point',
            old_name='JenisPelanggaran',
            new_name='Jenis_Pelanggaran',
        ),
        migrations.RenameField(
            model_name='point',
            old_name='NamaAssessor',
            new_name='Nama_Assessor',
        ),
        migrations.RenameField(
            model_name='point',
            old_name='NamaDituju',
            new_name='Nama_Dituju',
        ),
        migrations.RenameField(
            model_name='point',
            old_name='NamaPelanggaran',
            new_name='Nama_Pelanggaran',
        ),
        migrations.RenameField(
            model_name='point',
            old_name='NamaPengaju',
            new_name='Nama_Pengaju',
        ),
        migrations.RenameField(
            model_name='point',
            old_name='NomerIndukAssessor',
            new_name='Nomer_Induk_Assessor',
        ),
        migrations.RenameField(
            model_name='point',
            old_name='NomerIndukDituju',
            new_name='Nomer_Induk_Dituju',
        ),
        migrations.RenameField(
            model_name='point',
            old_name='NomerIndukPengaju',
            new_name='Nomer_Induk_Pengaju',
        ),
        migrations.RenameField(
            model_name='point',
            old_name='PointAkhir',
            new_name='Point_Akhir',
        ),
        migrations.RenameField(
            model_name='point',
            old_name='PointAwalDituju',
            new_name='Point_Awal_Dituju',
        ),
        migrations.RenameField(
            model_name='point',
            old_name='PointPengurang',
            new_name='Point_Pengurang',
        ),
        migrations.RenameField(
            model_name='point',
            old_name='TanggalDiterima',
            new_name='Tanggal_Diterima',
        ),
        migrations.RenameField(
            model_name='point',
            old_name='TanggalPengajuan',
            new_name='Tanggal_Pengajuan',
        ),
    ]
