# Generated by Django 3.0.4 on 2020-04-10 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0006_auto_20200322_1313'),
        ('point', '0009_auto_20200410_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='Id_Pelanggaran',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='point.Pelanggaran'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='point',
            name='Nama_Pelanggaran',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='point',
            name='Nomer_Induk_Assessor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Assessor', to='biodata.Biodata'),
        ),
    ]
