# Generated by Django 3.0.4 on 2020-04-13 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0006_auto_20200322_1313'),
        ('point', '0010_auto_20200410_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='Id_Pelanggaran',
        ),
        migrations.AddField(
            model_name='point',
            name='Keterangan',
            field=models.TextField(blank=True, default=None, max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='point',
            name='Jenis_Pelanggaran',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='point',
            name='Nama_Pelanggaran',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='point.Pelanggaran', to_field='Nama_Pelanggaran'),
        ),
        migrations.AlterField(
            model_name='point',
            name='Nomer_Induk_Dituju',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Dituju', to='biodata.Biodata', to_field='NomerInduk'),
        ),
        migrations.AlterField(
            model_name='point',
            name='Nomer_Induk_Pengaju',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Pengaju', to='biodata.Biodata', to_field='NomerInduk'),
        ),
    ]
