# Generated by Django 3.0.4 on 2020-04-13 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0006_auto_20200322_1313'),
        ('point', '0011_auto_20200413_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='Nama_Pelanggaran',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='point.Pelanggaran', to_field='Nama_Pelanggaran'),
        ),
        migrations.AlterField(
            model_name='point',
            name='Nomer_Induk_Assessor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Assessor', to='biodata.Biodata', to_field='NomerInduk'),
        ),
        migrations.AlterField(
            model_name='point',
            name='Nomer_Induk_Dituju',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Dituju', to='biodata.Biodata', to_field='NomerInduk'),
        ),
        migrations.AlterField(
            model_name='point',
            name='Nomer_Induk_Pengaju',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Pengaju', to='biodata.Biodata', to_field='NomerInduk'),
        ),
    ]
