# Generated by Django 3.0.4 on 2020-05-20 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0012_auto_20200413_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='Status',
            field=models.CharField(choices=[('Menunggu', 'Menunggu'), ('Rejected', 'Rejected'), ('Accepted', 'Accepted')], default='Menunggu', max_length=11),
        ),
    ]
