# Generated by Django 3.0.4 on 2020-05-20 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0006_auto_20200322_1313'),
        ('point', '0013_auto_20200520_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='Nomer_Induk_Assessor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='PointAssessor', to='biodata.Biodata', to_field='NomerInduk'),
        ),
        migrations.AlterField(
            model_name='point',
            name='Nomer_Induk_Dituju',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='PointDituju', to='biodata.Biodata', to_field='NomerInduk'),
        ),
        migrations.AlterField(
            model_name='point',
            name='Nomer_Induk_Pengaju',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='PointPengaju', to='biodata.Biodata', to_field='NomerInduk'),
        ),
    ]
