# Generated by Django 3.0.4 on 2020-03-19 14:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biodata',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('NomerInduk', models.CharField(max_length=50, unique=True)),
                ('Nama', models.CharField(max_length=100)),
                ('Agama', models.CharField(choices=[('Buddha', 'Buddha'), ('Hindu', 'Hindu'), ('Islam', 'Islam'), ('Katolik', 'Katolik'), ('KongHuCu', 'KongHuCu'), ('Kristen', 'Kristen'), ('Lainnya', 'Lainnya')], default='Lainnya', max_length=20)),
                ('TempatLahir', models.CharField(max_length=50)),
                ('TanggalLahir', models.DateField()),
                ('Alamat', models.CharField(max_length=300, null=True)),
                ('NomerTLP', models.CharField(max_length=15, null=True, unique=True)),
                ('Email', models.EmailField(max_length=100, null=True, unique=True)),
                ('PendidikanTerakhir', models.CharField(choices=[('SD', 'SD'), ('SMP', 'SMP'), ('SMA', 'SMA'), ('S1', 'S1'), ('S2', 'S2'), ('S3', 'S3')], max_length=5, null=True)),
                ('InstansiPendidikanTerakhir', models.CharField(max_length=200, null=True)),
                ('Point', models.SmallIntegerField(default=300)),
                ('Status', models.CharField(choices=[('Staf', (('Guru Aktif', 'Guru Aktif'), ('Guru Pensiun', 'Guru Pensiun'), ('Guru Diberhentikan', 'Guru Diberhentikan'), ('Staf Aktif', 'Staf Aktif'), ('Staf Pensiun', 'Staf Pensiun'), ('Staf Diberhentikan', 'Staf Diberhentikan'))), ('Siswa', (('Siswa Aktif', 'Siswa Aktif'), ('Siswa Lulus', 'Siswa Lulus'), ('Siswa Diberhentikan', 'Siswa Diberhentikan')))], max_length=30, null=True)),
                ('Profilepicture', models.ImageField(default='default.jpg', null=True, upload_to='profilepicture')),
            ],
        ),
    ]
