# Generated by Django 3.0.4 on 2020-03-21 00:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biodata',
            name='Agama',
            field=models.CharField(blank=True, choices=[('Buddha', 'Buddha'), ('Hindu', 'Hindu'), ('Islam', 'Islam'), ('Katolik', 'Katolik'), ('KongHuCu', 'KongHuCu'), ('Kristen', 'Kristen'), ('Lainnya', 'Lainnya')], max_length=20),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='Alamat',
            field=models.CharField(blank=True, default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='biodata',
            name='Email',
            field=models.EmailField(blank=True, default=' ', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='biodata',
            name='InstansiPendidikanTerakhir',
            field=models.CharField(blank=True, default=' ', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='biodata',
            name='NomerTLP',
            field=models.CharField(blank=True, default=' ', max_length=15, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='biodata',
            name='PendidikanTerakhir',
            field=models.CharField(blank=True, choices=[('SD', 'SD'), ('SMP', 'SMP'), ('SMA', 'SMA'), ('S1', 'S1'), ('S2', 'S2'), ('S3', 'S3')], default=' ', max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='biodata',
            name='Profilepicture',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='profilepicture'),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='Status',
            field=models.CharField(blank=True, choices=[('Staf', (('Guru Aktif', 'Guru Aktif'), ('Guru Pensiun', 'Guru Pensiun'), ('Guru Diberhentikan', 'Guru Diberhentikan'), ('Staf Aktif', 'Staf Aktif'), ('Staf Pensiun', 'Staf Pensiun'), ('Staf Diberhentikan', 'Staf Diberhentikan'))), ('Siswa', (('Siswa Aktif', 'Siswa Aktif'), ('Siswa Lulus', 'Siswa Lulus'), ('Siswa Diberhentikan', 'Siswa Diberhentikan')))], default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
