# Generated by Django 3.0.4 on 2020-03-22 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0004_auto_20200322_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biodata',
            name='Email',
            field=models.EmailField(blank=True, default=None, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='NomerTLP',
            field=models.CharField(blank=True, default=None, max_length=15, null=True, unique=True),
        ),
    ]
